# CC=g++
# CFLAGS=-I -Wall -pthread -lpigpio -lrt

# Sensor: Sensor.o
# 	$(CC) $(CFLAGS) -o Sensor Sensor.o
	
# Sensor.o: Sensor.hpp Sensor.cpp Node.hpp
# 	$(CC) $(CFLAGS) -c Sensor.cpp

# clean: 
# 	$(RM) Sensor *.o *~
